version: '3'
volumes: 
    crookedDbData:
services:
    database:
        image: "postgres:10-alpine"
        ports:
            - 5432:5432
        environment: 
            POSTGRES_USER: hamzeh
            POSTGRES_PASSWORD: hamzeh1378
            PGPASSWORD: hamzeh1378
            POSTGRES_DB: crooked
            PGDATA: /db_data
        volumes: 
            - crookedDbData:/db_data
    cache:
        image: "memcached:alpine"
        ports: 
            - 11211:11211
    broker:
        image: "rabbitmq:alpine"
        ports:
            - 5672:5672
    mailhog:
        image: "mailhog/mailhog"
        ports: 
            - 1025:1025
            - 8025:8025        